apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: streaming-platform

resources:
- deployment.yaml
- service.yaml
- persistent-volume.yaml
- ingress.yaml

commonLabels:
  app: streaming-platform
  version: v1.0.0

images:
- name: streaming-platform
  newTag: latest 