apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streaming-data-pvc
  labels:
    app: streaming-platform
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streaming-logs-pvc
  labels:
    app: streaming-platform
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streaming-exports-pvc
  labels:
    app: streaming-platform
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard 